### ISSUE TITLE
code this on C++

### ISSUE THREAD

**Issue by parbati09** [parbati09/C-#1]
Given an integer x, return true if x is palindrome integer.

An integer is a palindrome when it reads the same backward as forward.

For example, 121 is a palindrome while 123 is not.
 

Example 1:

Input: x = 121
Output: true
Explanation: 121 reads as 121 from left to right and from right to left.
Example 2:

Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.
Example 3:

Input: x = 10
Output: false
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.
 

Constraints:

-231 <= x <= 231 - 1

**Comment by isaacmtp** [comment]
I would really appreciate if you assign this to me

**Comment by Debayan97531** [comment]
i can do this..please assign it to me

**Comment by Debayan97531** [comment]
please merge my pull request

**Comment by Hussain6** [comment]
@parbati09 Can you assign this issue to me. I would like to contribute to this repo with palindrome integer finder in cpp.

**Comment by Debayan97531** [comment]
okay

**Comment by parbati09** [comment]
okay go for it

**Comment by isaacmtp** [comment]
I've made a pull request, made the necessary changes, pls do merge it

**Comment by isaacmtp** [comment]
I've made a pull request!

**Comment by akash-1107** [comment]
Please Assign this to me

**Comment by Kabir1302** [comment]
please assign it to me.

**Comment by sabhisharma-ise** [comment]
Can you please assign this issue to me?

**Comment by parbati09** [comment]
sure

**Comment by sabhisharma-ise** [comment]
Done with Pull Request #17 (along with Code & Output in Comment). Cheers!
