### ISSUE TITLE
Code the below Tree probllems in C++

### ISSUE THREAD

**Issue by parbati09** [parbati09/C-#6]
https://leetcode.com/problems/binary-tree-level-order-traversal
https://leetcode.com/problems/binary-tree-level-order-traversal-ii
https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal
https://leetcode.com/problems/n-ary-tree-level-order-traversal

**Comment by akashyadav24** [comment]
can you assign it to me ?

**Comment by akash-1107** [comment]
please assign it to me.
