### ISSUE TITLE
Problems on Linked List

### ISSUE THREAD

**Issue by parbati09** [parbati09/C-#7]
Add some good problems with codes mentioning the time complexity on linked list in C++

**Comment by akash-1107** [comment]
can you please assign it to me?

**Comment by yogesh-9999** [comment]
assign it to me

**Comment by parbati09** [comment]
go for it..I will merge

**Comment by Rakteem007** [comment]
can i contribute to this issue?

**Comment by parbati09** [comment]
sure

**Comment by sona-123** [comment]
@parbati09 mam please assign this issue to me I want to add some conversion from stack to linked list or queue to linked list

**Comment by parbati09** [comment]
@sona-123 ok

**Comment by rahulr2109** [comment]
can you assign this to me.

**Comment by iisha27** [comment]
please assign this to me.

**Comment by jahnavimehta** [comment]
Hello! I would like to contribute. Can you please assign this to me?
